steps:
  # Install Node.js dependencies in the 'functions' directory
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'functions'
  # Run the build (TypeScript compilation) script in the 'functions' directory
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'functions'
  # Deploy only the functions to your Firebase project
  - name: 'gcr.io/cloud-builders/firebase'
    args: ['deploy', '--only', 'functions', '--project', '${_PROJECT_ID}']
    dir: 'functions'
options: # <--- This section needs to be added or updated
  logging: CLOUD_LOGGING_ONLY # This directs logs to Cloud Logging
timeout: '1600s' # Adjust timeout if deployment takes longer
