steps:
  # Install Node.js dependencies in the 'functions' directory
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'functions'
  # Run the build (TypeScript compilation) script in the 'functions' directory
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'functions'
  # Deploy only the functions to your Firebase project
  - name: 'gcr.io/cloud-builders/firebase'
    args: ['deploy', '--only', 'functions', '--project', '${_PROJECT_ID}']
    dir: 'functions'
    # Optional: Set Node.js environment to production if needed for deployment
    # env:
    #   - 'NODE_ENV=production'
timeout: '1600s' # Adjust timeout if deployment takes longer
