steps:
  # Install Node.js dependencies in the 'functions' directory
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'functions'
  # Run the build (TypeScript compilation) script in the 'functions' directory
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'functions'
  # Deploy only the functions to your Firebase project
  - name: 'gcr.io/cloud-builders/firebase'
    args: ['deploy', '--only', 'functions', '--project', '${_PROJECT_ID}']
    dir: 'functions'
options: # <--- Add this section
  logging: CLOUD_LOGGING_ONLY # This tells Cloud Build to send logs to Cloud Logging
                              # It satisfies the requirement when a service account is used.
  # default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET # Alternative, but CLOUD_LOGGING_ONLY is often simpler
timeout: '1600s' # Adjust timeout if deployment takes longer
